### ISSUE TITLE
Configuration native de l'éditeur - config.js

### ISSUE THREAD

**Issue by KonstantinFromRussia** [Pluxopolis/ckeditor#4]
Bonjour,
Est-il possible d'utiliser le fichier de configuration native de l'éditeur - config.js ?
J'ai besoin d'ajouter des commandes au code:

```
> // interdire la suppression des tags s'il n'y a rien entre eux
> 	CKEDITOR.dtd.$removeEmpty.span = 0;
> 	CKEDITOR.dtd.$removeEmpty.i = 0;
> 	CKEDITOR.dtd.$removeEmpty.div = 0;
> 	CKEDITOR.dtd.$removeEmpty.em = 0;
> 	CKEDITOR.dtd.$removeEmpty.b = 0;
> // Autoriser les tags et les codes individuels
>         config.protectedSource.push(/<(style)[^>]*>.*<\/style>/ig); // Style tag
> 	config.protectedSource.push(/<(script)[^>]*>.*<\/script>/ig); // Script code
> 	config.protectedSource.push(/<\?[\s\S]*?\?>/g); // PHP code
> 	config.protectedSource.push(/<%[\s\S]*?%>/g); // ASP code
> 	config.protectedSource.push(/(]+>[\s|\S]*?<\/asp:[^\>]+>)|(]+\/>)/gi); // ASP.Net code
```

**Comment by Pluxopolis** [comment]
Bonjour
Oui ça me semble possible dans le fichier ckeditor/ckeditor/config.js
Mais le risque est de perdre ces modifications quand ckeditor sera mis à jour car le fichier config.js sera écrasé par le nouveau. Il faudra alors reporter à nouveau les modifications

**Comment by KonstantinFromRussia** [comment]
Oui, c'est seulement lorsque je modifie le fichier config.js - rien ne change. 
Par exemple, je veux changer la peau. 
Comment faire cela?

**Comment by Pluxopolis** [comment]
Pensez à vider le cache du navigateur

**Comment by KonstantinFromRussia** [comment]
Oui, merci, aidé.
Je veux dire que pour effacer complètement le cache, j'ai dû installer une extension de Click&Clean sur Google Chrome.
Les méthodes habituelles de nettoyage n'ont pas aidé.
Seulement Click&Clean
